[package]
name = "emu8080"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24.0"
strum_macros = "0.24.3"
pest = "2.0"
pest_derive = "2.4"